name: Deploy with Jira Gating

on:
  deployment_status:
    types: [success]  # Triggered when the deployment status is marked as successful

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy if Approved
        run: |
          echo "Deployment approved by Jira. Proceeding with deployment."
          # Your deployment script here
