name: Deploy with Jira Gating

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Jira Gating Status
        uses: actions/github-script@v3
        with:
          script: |
            // Assume 'context' and 'github' are available in this script
            const jiraGatingStatus = await checkJiraGatingStatus();
            if (jiraGatingStatus !== 'ALLOWED') {
              core.setFailed('Deployment not allowed by Jira');
            }
      
      - name: Deploy if Allowed
        run: |
          echo "Deploying to production..."
          # Add your deployment script here
