name: Deploy to Production

on:
  push:
    branches:
      - main  # Adjust this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Staging  # This should match the environment in your settings

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust based on your needs

      - name: Install dependencies
        run: npm install

      # Example of using deployment gating
      - name: Deploy to Stg
        if: github.event_name == 'deployment' && github.event.deployment_status.state == 'success'
        run: |
          echo "Deploying to stg"
          # Your deployment script here, e.g., npm run deploy
